# 1. Setup

## 1.1 Import libraries

In [1]:
from IPython.display import clear_output

In [2]:
!pip install fbgemm-gpu
#!pip install fbgemm-gpu-cpu

!pip install torch
!pip install torchrec
#!pip install torchrec-cpu
!pip install pyre_extensions

#clear_output()

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
import pandas as pd
import numpy as np
import random

import torch
from torch.utils.data.dataset import IterableDataset
from torchrec.datasets.utils import Batch
from torchrec.sparse.jagged_tensor import KeyedJaggedTensor

In [4]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Device: '{device}'")

Device: 'cuda'


In [5]:
!rm -r recommender_systems_dlrm

In [6]:
GITHUB_TOKEN = "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"
USER = "linafaik08"
CLONE_URL = f"https://{USER}:{GITHUB_TOKEN}@github.com/{USER}/recommender_systems_dlrm.git"
get_ipython().system(f"git clone {CLONE_URL}")

Cloning into 'recommender_systems_dlrm'...
remote: Enumerating objects: 46, done.
remote: Counting objects: 100% (46/46), done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 46 (delta 10), reused 41 (delta 8), pack-reused 0
Unpacking objects: 100% (46/46), 11.66 KiB | 994.00 KiB/s, done.


In [7]:
cd recommender_systems_dlrm/src

/content/recommender_systems_dlrm/src


In [8]:
from batch import *
from model import *

## 1.2. Generate data

In [9]:
n_rows = 10000

train_df = pd.DataFrame({
    "feat1": np.random.rand(n_rows),
    "feat2": np.random.rand(n_rows),
    "cat1": np.random.choice(["A","B","C"], n_rows),
    "cat2": [random.choice([["A","B","C"], ["A","B"],  ["A","C"], ["B","C"], ["B"], []]) for i in range(n_rows)],
    "label": np.random.choice([0,1], n_rows)
})

n_rows = int(n_rows*0.2)

test_df = pd.DataFrame({
    "feat1": np.random.rand(n_rows),
    "feat2": np.random.rand(n_rows),
    "cat1": np.random.choice(["A","B","C"], n_rows),
    "cat2": [random.choice([["A","B","C"], ["A","B"],  ["A","C"], ["B","C"], ["B"], []]) for i in range(n_rows)],
    "label": np.random.choice([0,1], n_rows)
})

n_rows = int(n_rows*0.2)

val_df = pd.DataFrame({
    "feat1": np.random.rand(n_rows),
    "feat2": np.random.rand(n_rows),
    "cat1": np.random.choice(["A","B","C"], n_rows),
    "cat2": [random.choice([["A","B","C"], ["A","B"],  ["A","C"], ["B","C"], ["B"], []]) for i in range(n_rows)],
    "label": np.random.choice([0,1], n_rows)
})

In [10]:
train_df.head()

feat1     feat2 cat1       cat2  label
0  0.345094  0.009729    C         []      1
1  0.896301  0.485715    A  [A, B, C]      0
2  0.424472  0.073893    B     [A, C]      1
3  0.077299  0.343394    C  [A, B, C]      1
4  0.940979  0.316964    A     [A, C]      1

In [11]:
cols_dense = ["feat1", "feat2"]
cols_sparse = ['cat1', 'cat2']

# 2. Features

## 2.1. Encoding sparse features

In [12]:
def encode(col, map_rev):
    return [map_rev.get(item,item) for item in col]

In [13]:
map_sparse = {}
map_sparse_rev = {}

In [14]:
for feat in cols_sparse:
    map_sparse[feat] = {i: c for i,c in enumerate(train_df[feat].explode().value_counts().index)}
    map_sparse_rev[feat] = {v:k for k, v in map_sparse[feat].items()}

    train_df[feat+'_enc'] = train_df[feat].apply(lambda x: encode(x, map_sparse_rev[feat]))
    test_df[feat+'_enc'] = test_df[feat].apply(lambda x: encode(x, map_sparse_rev[feat]))
    val_df[feat+'_enc'] = test_df[feat].apply(lambda x: encode(x, map_sparse_rev[feat]))

In [15]:
map_sparse

{'cat1': {0: 'C', 1: 'A', 2: 'B'}, 'cat2': {0: 'B', 1: 'A', 2: 'C'}}

## 2.2. Build data batches

In [16]:
train_data = RecBatch(
    data = train_df,
    cols_sparse = [c+'_enc' for c in cols_sparse],
    cols_dense = cols_dense,
    col_label = "label",
    batch_size = 100,
    num_generated_batches = 20,
    seed = 123,
    device = device
)

replace False


In [17]:
test_data = RecBatch(
    data = test_df,
    cols_sparse = [c+'_enc' for c in cols_sparse],
    cols_dense = cols_dense,
    col_label = "label",
    batch_size = 100,
    num_generated_batches = 3,
    seed = 123,
    device = device
)

replace False


In [18]:
val_data = RecBatch(
    data = val_df,
    cols_sparse = [c+'_enc' for c in cols_sparse],
    cols_dense = cols_dense,
    col_label = "label",
    batch_size = 100,
    num_generated_batches = None,
    seed = 123,
    device = device
)

### Check

In [19]:
i=0

batch = build_batch(val_data.batches[i], cols_sparse)
sparse_features = batch.sparse_features

In [20]:
sparse_features[val_data.cols_sparse[0]].to_dense()[:5]

[tensor([0], device='cuda:0'),
 tensor([0], device='cuda:0'),
 tensor([0], device='cuda:0'),
 tensor([0], device='cuda:0'),
 tensor([0], device='cuda:0')]

In [21]:
val_df.iloc[:5]

feat1     feat2 cat1       cat2  label cat1_enc   cat2_enc
0  0.210193  0.857437    B  [A, B, C]      1      [0]         []
1  0.011015  0.381668    B     [A, B]      1      [0]     [0, 2]
2  0.981134  0.482242    A     [A, B]      0      [0]         []
3  0.742414  0.058562    C         []      0      [0]  [1, 0, 2]
4  0.522714  0.236849    A     [A, B]      0      [0]     [1, 2]

In [22]:
sparse_features[val_data.cols_sparse[1]].to_dense()[:5]

[tensor([], device='cuda:0', dtype=torch.int64),
 tensor([0, 2], device='cuda:0'),
 tensor([], device='cuda:0', dtype=torch.int64),
 tensor([1, 0, 2], device='cuda:0'),
 tensor([1, 2], device='cuda:0')]

# 3. Training / Test

In [23]:
embedding_dim = 10
num_embeddings_per_feature = {c+'_enc': len(v) for c, v in map_sparse.items()}

dense_arch_layer_sizes = [512, 256, embedding_dim]
over_arch_layer_sizes = [512, 512, 256, 1]

adagrad = False
eps = 1e-8 # Epsilon for Adagrad optimizer

learning_rate = 0.01# 0.01 #15.0

In [24]:
model_dlrm = DLRMCustom(
        cols_dense, cols_sparse,
        embedding_dim, num_embeddings_per_feature,
        dense_arch_layer_sizes, over_arch_layer_sizes,
        adagrad, learning_rate, eps,
        device)

In [25]:
n_epochs = 100
e_patience = 10

In [26]:
scores = model_dlrm.train_test(train_data, test_data, n_epochs, e_patience, nb_batches = None)

 27%|██▋       | 27/100 [00:03<00:09,  7.36it/s, epoch=28, loss_train=0.693, losses_test=0.697, auc_train=0.509, auc_test=0.45]

Early stopping


In [27]:
results = pd.DataFrame(scores).T
results = results.reset_index().rename(columns = {'index':'epoch'})

plot_results(results)

# 5. Cross-Validation

In [28]:
batch_size = 500
num_generated_batches_train = 100
num_generated_batches_val = 10
n_epochs, e_patience = 100, 10

In [29]:
batch_size*num_generated_batches_train

50000

In [30]:
train_df = pd.concat([train_df, test_df], axis=0).reset_index(drop=True)

In [31]:
from sklearn.model_selection import cross_val_score, KFold, StratifiedKFold

seed = 123
kfolds = StratifiedKFold(n_splits=3, shuffle=True, random_state=seed)

test_aucs = {}

for i, (train_index, test_index) in enumerate(kfolds.split(train_df, train_df.label)):
    print("---"*10)
    print(f"Fold {i+1}/{kfolds.n_splits}")

    train_df_kf = train_df.iloc[train_index].reset_index(drop=True)
    test_df_kf = train_df.iloc[test_index].reset_index(drop=True)

    print('   Generate train data ...')

    train_data = RecBatch(
        data = train_df_kf,
        cols_sparse = [c+'_enc' for c in cols_sparse],
        cols_dense = cols_dense,
        col_label = "label",
        batch_size = batch_size,
        num_generated_batches = num_generated_batches_train,
        seed = seed,
        device= device
    )

    print('   Generate test data ...')

    test_data = RecBatch(
        data = test_df_kf,
        cols_sparse = [c+'_enc' for c in cols_sparse],
        cols_dense = cols_dense,
        col_label = "label",
        batch_size = batch_size,
        num_generated_batches = num_generated_batches_val,
        seed = seed,
        device= device
    )

    model_dlrm = DLRMCustom(
        cols_dense, cols_sparse,
        embedding_dim, num_embeddings_per_feature,
        dense_arch_layer_sizes, over_arch_layer_sizes,
        adagrad, learning_rate, eps,
        device)

    scores = model_dlrm.train_test(train_data, test_data, n_epochs, e_patience)
    scores = pd.DataFrame(scores).T.reset_index().rename(columns = {'index':'epoch'})

    print('   Scores:')
    print(scores.iloc[-5:])

    labels, preds, losses_test, auc_test = model_dlrm.evaluate(test_data)
    print("   Test AUC:", round(auc_test, 4))

    test_aucs[i] = auc_test


------------------------------
Fold 1/3
   Generate train data ...
replace True
   Generate test data ...
replace True


 37%|███▋      | 37/100 [00:23<00:39,  1.58it/s, epoch=38, loss_train=0.69, losses_test=0.695, auc_train=0.54, auc_test=0.495]


Early stopping
   Scores:
    epoch  loss_train  loss_test  auc_train  auc_test
33     33    0.690787   0.695547     0.5349    0.4880
34     34    0.690687   0.695213     0.5356    0.4953
35     35    0.690454   0.695372     0.5374    0.4900
36     36    0.690305   0.695614     0.5378    0.4956
37     37    0.690195   0.695188     0.5401    0.4948
   Test AUC: 0.4948
------------------------------
Fold 2/3
   Generate train data ...
replace True
   Generate test data ...
replace True


100%|██████████| 100/100 [00:45<00:00,  2.22it/s, epoch=100, loss_train=0.666, losses_test=0.726, auc_train=0.629, auc_test=0.486]


   Scores:
    epoch  loss_train  loss_test  auc_train  auc_test
95     95    0.671248   0.722104     0.6156    0.4819
96     96    0.672289   0.723416     0.6134    0.4815
97     97    0.666575   0.725101     0.6283    0.4835
98     98    0.668541   0.718543     0.6226    0.4897
99     99    0.666183   0.726075     0.6287    0.4856
   Test AUC: 0.4856
------------------------------
Fold 3/3
   Generate train data ...
replace True
   Generate test data ...
replace True


 44%|████▍     | 44/100 [00:21<00:26,  2.08it/s, epoch=45, loss_train=0.685, losses_test=0.701, auc_train=0.572, auc_test=0.496]

Early stopping
   Scores:
    epoch  loss_train  loss_test  auc_train  auc_test
40     40    0.686949   0.698008     0.5640    0.5005
41     41    0.686463   0.700921     0.5666    0.4967
42     42    0.685534   0.698902     0.5704    0.4965
43     43    0.687135   0.700489     0.5634    0.4970
44     44    0.685308   0.700969     0.5719    0.4963
   Test AUC: 0.4963


In [32]:
test_aucs = pd.DataFrame.from_dict(test_aucs, orient='index').\
              reset_index().\
              rename(columns = {'index': 'epoch', 0:'val_auc'})

test_aucs

epoch   val_auc
0      0  0.494823
1      1  0.485603
2      2  0.496337

In [33]:
!pip freeze

absl-py==1.4.0
aiohttp==3.8.4
aiosignal==1.3.1
alabaster==0.7.13
albumentations==1.2.1
altair==4.2.2
anyio==3.7.0
appdirs==1.4.4
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
array-record==0.4.0
arviz==0.15.1
astropy==5.2.2
astunparse==1.6.3
async-timeout==4.0.2
attrs==23.1.0
audioread==3.0.0
autograd==1.6
Babel==2.12.1
backcall==0.2.0
beautifulsoup4==4.11.2
bleach==6.0.0
blis==0.7.9
blosc2==2.0.0
bokeh==2.4.3
branca==0.6.0
build==0.10.0
CacheControl==0.13.1
cached-property==1.5.2
cachetools==5.3.1
catalogue==2.0.8
certifi==2023.5.7
cffi==1.15.1
chardet==4.0.0
charset-normalizer==2.0.12
chex==0.1.7
click==8.1.3
click-plugins==1.1.1
cligj==0.7.2
cloudpickle==2.2.1
cmake==3.25.2
cmdstanpy==1.1.0
colorcet==3.0.1
colorlover==0.3.0
community==1.0.0b1
confection==0.0.4
cons==0.4.6
contextlib2==0.6.0.post1
contourpy==1.1.0
convertdate==2.4.0
cufflinks==0.17.3
cupy-cuda11x==11.0.0
cvxopt==1.3.1
cvxpy==1.3.1
cycler==0.11.0
cymem==2.0.7
Cython==0.29.35
dask==2022.12.1
datascience==0.17.6
db-d